const languageData = {

  pt: {

    navSolutions: 'Soluções',
    navContact: 'Contact',
    navPlans: 'Planos',
    dropdown01: 'Mais',
    navAboutUs: 'Sobre nós',
    navTerms: 'Termos & Condições',
    navPrivacy: 'Política de Privacidade',
    pageTitle1: 'Transformamos ideias em realidade, trazendo criatividade excepcional para impulsionar o seu negócio. Seja único, destaque-se da concorrência e alcance seu público-alvo de forma memorável. Vamos fazer da sua marca uma referência de sucesso.',
    pageTitleButton: 'Saiba mais',
    FormTittle: 'Preencha o formulário e nós entraremos em contato.',
    FormP1: 'Pronto para levar sua empresa para o próximo nível? Basta clicar no botão abaixo para nos contatar e nossa equipe entrará em contato em breve. Estamos animados para discutir suas necessidades comerciais únicas, desenvolver ideias inovadoras e criar uma estratégia de marketing personalizada que gere resultados.',
    FormTitleP2:'<strong>Soluções Inovadoras: </strong>Temos orgulho de estar na vanguarda da inovação. Quando você entrar em contato conosco, forneceremos ideias novas e criativas para destacar sua marca da concorrência.',
    FormTitleP3:'<strong>Atenção Personalizada: </strong> O seu sucesso é a nossa prioridade. Quando você entrar em contato conosco, daremos a atenção personalizada que você merece.',
    FormTitleP4:'<strong>Colaboração:</strong> acreditamos no poder da colaboração. Ao entrar em contato conosco, você terá a oportunidade de colaborar com nossa equipe dedicada. Valorizamos suas informações e percepções e, juntos, criaremos uma parceria forte para alcançar o sucesso de longo prazo para sua marca.',
    FormName:'Nome',
    FormPhone:'Telefone',
    FormInterested:'Interessado em...',
    PrivacyTerms: 'Eu concordo com a <a href="privacy.html">Política de Privacidade</a> e os <a href="terms.html">Termos & Condições',
    FormInquireButton: 'Solicite um orçamento',
    SolutionsH1: 'U-Innova Studios: impulsionando o crescimento do seu negócio com soluções de Software, Marketing Digital, Web Design, Design Gráfico e Digital Media.',
    SoftwareSolution: 'Oferecemos uma solução de software personalizada para o gerenciamento eficiente do seu negócio. Nosso programa avançado simplifica e automatiza processos-chave, desde o gerenciamento de cadastros, estoque, usuários até o acompanhamento do crescimento da sua empresa.',
    MarketingSolution: 'Oferecemos uma solução de marketing abrangente para ajudar sua empresa a se destacar no mercado. Nossa solução personalizada combina estratégias criativas, análise de dados e tecnologia para impulsionar sua presença online, aumentar a visibilidade da marca e atrair clientes qualificados.',
    Details1: 'Impulsionando seu sucesso com soluções de Marketing, Design e Software.',
    DetaisP1: 'Aumente sua presença online, conquiste clientes e acelere seus negócios. Inovação e criatividade ao seu alcance com <a href="#your-link">U-Innova Studios',
    Details2: 'Software para gerenciamento com soluções personalizadas',
    DetaisP2: 'Com recursos robustos de rastreamento de candidatos, gestão de projetos e comunicação integrada, nosso <a target="_blank" href="https://u-innova.herokuapp.com/"><b>software</b></a> permite que as empresas otimizem sua eficiência operacional, melhorem a qualidade do serviço.',
    SolutionsH2: 'U-innova: Software de gerenciamento',
    pHeading1: 'A U-innova studios desenvolveu um software inovador que irá impulsionar o sucesso da sua empresa.',
    pHeading2: 'Com o software da u-innova você terá:',
    faIcon1: 'Gerenciamento de funcionários e candidatos',
    faIcon2: 'Relatórios e perfis detalhados',
    faIcon3: 'Painel de gerenciamento para cada usuário',
    faIcon4: 'Gerenciamento de vagas e local de trabalho',
    faIcon5: 'Banco de dados com backup diário',
    faIcon6: 'Fácil visualização de candidatos ativos e/ou inativos',
    faIcon7: 'Controle de cadastros em revisão',
    faIcon8: 'Estatísticas de performance e monitoramento de erros',
    FutureFeaturesTitle: 'RECURSOS FUTUROS',
    FutureFeatures1: 'Controle de yuukyu',
    FutureFeatures2: 'Controle de salário e horas extras',
    FutureFeatures3: 'Solicitação de folga',
    FutureFeatures4: 'Assinatura de contratos',
    FutureFeatures5: 'Solicitação de vale',
    PlansTitle: 'Planos',
    PlansSubTitle: 'Pacotes de serviços',
    BasicPlan: 'BASICO',
    BasicPlanTitle: 'Solução de Software para gerenciamento de empresas',
    BasicPlan1: '• Software para controle de funcionários, cadastros, fichas, etc',
    BasicPlan2: '• Suporte técnico especializado',
    BasicPlan3: '• Análise de dados e relatórios de desempenho',
    InquirePlansButton1: 'Escolher',
    AdvancedPlan: 'AVANÇADO',
    AdvancedPlanTitle: 'Gerenciamento de Redes Sociais, Marketing digital e artes',
    AdvancedPlan1: '• Gerenciamento de redes sociais',
    AdvancedPlan2: '• Criação de artes para posts nas redes sociais',
    AdvancedPlan3: '• Impulsionamento de publicações nas redes sociais',
    AdvancedPlan4: '• Design de material digital e impresso (ex.: panfletos, cartões de visita, banners)',
    AdvancedPlan5: '• Produção e entrega dos materiais impressos',
    InquirePlansButton2: 'Escolher',
    CompletePlan: 'COMPLETO',
    CompletePlanTitle: 'Solução Personalizada de Software, Marketing Digital e Design gráfico',
    CompletePlan1: '*Tudo que o plano BASIC e ADVANCED possuem',
    CompletePlan2: '• Campanhas de marketing personalizadas',
    CompletePlan3: '• Criação de website / landing page para a marca',
    CompletePlan4: '• Otimização de SEO (Search Engine Optimization)',
    CompletePlan5: '• Análise de dados e monitoramento do desempenho das campanhas',
    InquirePlansButton3: 'Escolher',
    cassianoAboutIndex: 'Engenheiro de software backend com experiência no desenvolvimento de soluções de gerenciamento para o setor imobiliário em Tokyo. Formado pela Le Wagon como full stack engineer.',
    narumiAboutIndex: 'Profissional apaixonada por web design, também com experiência nas áreas de design gráfico, marketing digital, mídia digital e desenvolvimento front-end.',
    aboutUsBtn1: 'Sobre nós <span class="material-symbols-outlined"><i class="fa-solid fa-arrow-right"></i>',
    aboutUsBtn2: 'Sobre nós <span class="material-symbols-outlined"><i class="fa-solid fa-arrow-right"></i>',
    testimonial1: 'O software da U-Innova revolucionou nosso gerenciamento de empreiteiras. Agora podemos facilmente acompanhar e gerenciar nossos funcionários e candidatos em um só lugar, tornando todo o processo mais eficiente.</p><p class="testimonial-author"> Empresa de recrutamento</p>',
    testimonial2: 'O painel de gerenciamento individual para cada tantousha no software da U-Innova é incrível. Agora podemos personalizar e controlar as atividades de cada membro da equipe, garantindo uma distribuição eficiente de tarefas e otimizando nossa produtividade.</p><p class="testimonial-author"> Empresa de recrutamento</p>',
    testimonial3: 'O gerenciamento de vagas e local de trabalho nunca foi tão fácil. Podemos atribuir rapidamente vagas aos candidatos e acompanhar o progresso de cada projeto, mantendo todos informados.</p><p class="testimonial-author"> Gerente de contratação</p>',
    testimonial4: 'O banco de dados integrado no software da U-Innova é um verdadeiro salva-vidas. Agora temos todas as informações dos candidatos e funcionários armazenadas de forma organizada e acessível, agilizando nosso fluxo de trabalho.</p><p class="testimonial-author">Cliente satisfeito</p>',
    testimonial5: 'A fácil visualização de candidatos ativos e/ou inativos é um dos recursos mais úteis do software. Podemos identificar rapidamente os candidatos que estão disponíveis para atribuições futuras, simplificando nosso processo de seleção.</p><p class="testimonial-author">Empreiteira</p>',
    testimonial6: 'O controle de cadastros em revisão no software da U-Innova é uma funcionalidade essencial. Agora podemos revisar, aprovar e atualizar os cadastros dos empreiteiros de forma rápida e eficiente, mantendo nosso banco de dados sempre atualizado.</p><p class="testimonial-author">Gerente de recursos humanos</p>',
    Statistics1: 'Clientes satisfeitos',
    Statistics2: 'Problemas resolvidos',
    Statistics3: 'Reviews positivos',
    Statistics4: 'Casos estudados',
    MissionLP: 'Nossa missão é fornecer soluções de software e marketing digital inovadoras que capacitem nossos clientes a alcançar o sucesso em um mundo digital em constante evolução.',
    AboutUsBtn3:'Sobre nós',
    SubscribeAndFollowButton: 'Siga e se Inscreva',
    SubscribeAndFollowText: 'Fique por dentro das novidades da U-Innova Studios! Siga-nos no <a href="#your-link">instagram</a> e curta nossa página no <a href="#your-link">Facebook</a> Junte-se à nossa comunidade digital e faça parte da nossa jornada de inovação e crescimento!',
    TalkWithUs: 'Fale Conosco',
    aboutWebsite: 'Sobre o site',
    aboutWebsiteText: 'Bem-vindo ao site da U-Innova Studios! Somos uma empresa apaixonada por inovação, software e marketing digital. Nossa missão é impulsionar o sucesso dos nossos clientes, fornecendo soluções criativas e eficazes. Explore nosso site para descobrir como podemos ajudar a transformar seu negócio no mundo digital!',
    ContactUsFooter: 'Entre em contato',
    
    //About Us page

    AboutUsTittle: 'Sobre nós',
    CassianoDescription:'Engenheiro de software backend com experiência no desenvolvimento de soluções de gerenciamento para o setor imobiliário em Tokyo. Formado pela Le Wagon como full stack engineer, possuo habilidades abrangentes em desenvolvimento de software. Tenho experiência significativa no desenvolvimento de soluções de gerenciamento para pessoas, bem como conhecimentos em segurança da informação e infraestrutura de dados. Minha paixão por tecnologia e meu compromisso com a excelência me impulsionam a criar soluções eficientes e seguras, para atender às necessidades do mercado.',
    NarumiDescription: 'Com experiência nas áreas de web design, design gráfico, marketing digital, digital media e desenvolvimento front-end, tenho habilidades técnicas para transformar conceitos em interfaces atraentes e funcionais. Minha paixão pelo design gráfico me permite criar layouts impactantes que comunicam a essência da marca. Com conhecimentos em marketing digital e mídia digital, estou apta a desenvolver estratégias eficazes para promover negócios online e alcançar o público-alvo de forma eficiente. Estou sempre atualizada com as últimas tendências e melhores práticas do setor, buscando aprimorar constantemente minhas habilidades para entregar projetos de alta qualidade.',

    //Policy & Privacy page

    PrivacyTitle: 'Política de privacidade',
    PrivacyP1: 'A privacidade dos nossos visitantes é muito importante para nós. Esta política de privacidade descreve como coletamos, usamos, divulgamos e protegemos as informações pessoais que você nos fornece ao usar o site U-Innova Studios.',
    PrivacyP2: 'Coletamos as informações que você fornece voluntariamente ao preencher nosso formulário de contato, incluindo seu nome, endereço de e-mail e número de telefone. Essas informações são coletadas com o objetivo de entrarmos em contato com você e fornecer informações sobre nossos serviços.',
    PrivacyP3: 'As informações que coletamos são utilizadas exclusivamente para entrarmos em contato com você e fornecer informações relevantes sobre nossos serviços de marketing e publicidade. Não compartilhamos suas informações pessoais com terceiros, exceto quando necessário para cumprir obrigações legais ou com o seu consentimento expresso.',
    PrivacyP4: 'Implementamos medidas de segurança adequadas para proteger suas informações contra acesso não autorizado, uso indevido ou divulgação. Adotamos práticas de segurança da informação para garantir a integridade e confidencialidade dos dados coletados.',
    PrivacyP5: 'Nosso site pode utilizar cookies para melhorar a experiência do usuário. Os cookies são pequenos arquivos de texto armazenados no seu dispositivo que nos permitem reconhecer informações específicas sobre sua visita ao site. Você pode optar por desativar os cookies nas configurações do seu navegador, no entanto, isso pode afetar o funcionamento correto do site.',
    PrivacyP6: 'O site U-Innova Studios pode conter links para sites de terceiros. Esta política de privacidade se aplica exclusivamente ao nosso site. Não somos responsáveis pelas práticas de privacidade desses sites. Recomendamos que você leia as políticas de privacidade desses sites antes de fornecer qualquer informação pessoal.',
    PrivacyP7: 'Ao utilizar o site U-Innova Studios e fornecer suas informações pessoais, você concorda com a coleta, uso e divulgação dessas informações de acordo com esta política de privacidade.',
    PrivacyP8: 'Reservamo-nos o direito de atualizar ou modificar esta política de privacidade a qualquer momento. Recomendamos que você revise esta política periodicamente para se manter informado sobre quaisquer alterações. O uso continuado do site após a publicação de alterações constitui o seu consentimento em relação a tais alterações.',
    PrivacyP9: 'Se você tiver alguma dúvida ou preocupação sobre nossa política de privacidade ou o processamento de seus dados pessoais, entre em contato conosco através das informações fornecidas no site.',
    Privacyh1: '1. Coleta de informações',
    Privacyh2: '2. Uso das informações',
    Privacyh3: 'Proteção das informações',
    Privacyh4: 'Cookies',
    Privacyh5: 'Links para sites de terceiros',
    Privacyh6: 'Consentimento',
    Privacyh7: 'Alterações na política de privacidade',
    Privacyh8: 'Contato',

    //Terms

    TermsTittle: 'Termos & Condições',
    TermsP1: 'Ao acessar e utilizar o site U-Innova Studios, você concorda em cumprir estes termos e condições de uso. Caso não concorde com algum dos termos descritos abaixo, recomendamos que você interrompa o uso do site.',
    TermsP2: 'O site U-Innova Studios destina-se a fornecer informações sobre nossos serviços de marketing e publicidade. Você concorda em utilizar o site apenas para fins legítimos e de acordo com todas as leis e regulamentações aplicáveis.',
    TermsP3: 'Ao preencher nosso formulário de contato, você concorda em fornecer informações precisas e atualizadas, incluindo seu nome, endereço de e-mail e número de telefone. Essas informações são coletadas com o objetivo de entrarmos em contato com você e fornecer informações sobre nossos serviços. Respeitamos sua privacidade e não compartilhamos suas informações pessoais com terceiros, exceto quando necessário para cumprir obrigações legais ou com o seu consentimento expresso.',
    TermsP4: 'Todos os direitos autorais, marcas registradas e outros direitos de propriedade intelectual relacionados ao conteúdo e design do site U-Innova Studios são de propriedade exclusiva da nossa empresa ou de terceiros devidamente autorizados. É proibido copiar, reproduzir, modificar, distribuir ou utilizar qualquer conteúdo do site sem a nossa autorização por escrito.',
    TermsP5: 'O site U-Innova Studios pode conter links para sites de terceiros. Esses links são fornecidos apenas para conveniência e não implicam em endosso ou responsabilidade pelos conteúdos desses sites. Recomendamos que você revise os termos e condições e políticas de privacidade desses sites antes de utilizá-los',
    TermsP6: 'O site U-Innova Studios é fornecido "no estado em que se encontra" e não oferece garantias de qualquer tipo, expressas ou implícitas. Não nos responsabilizamos por quaisquer danos diretos, indiretos, incidentais, consequenciais ou punitivos decorrentes do uso ou impossibilidade de uso do site.',
    TermsP7: 'Reservamo-nos o direito de atualizar ou modificar estes termos e condições a qualquer momento, sem aviso prévio. Recomendamos que você revise periodicamente esta página para se manter atualizado sobre quaisquer alterações. O uso contínuo do site após a publicação de alterações constitui a sua aceitação dessas alterações.',
    TermsP8: 'Estes termos e condições são regidos pelas leis do Brasil. Qualquer disputa relacionada ao uso do site U-Innova Studios estará sujeita à jurisdição exclusiva dos tribunais competentes do Brasil.',
    hTerms1: '1. Uso do site',
    hTerms2: '2. Informações de contato',
    hTerms3: 'Propriedade intelectual',
    hTerms4: 'Links para sites de terceiros',
    hTerms5: 'Limitação de responsabilidade',
    hTerms6: 'Alterações nos termos e condições',
    hTerms7: 'Lei aplicável e jurisdição',
    

    english: 'English',
    portuguese: 'Português',
  },

  en: {

    navSolutions: 'Solutions',
    navContact: 'Contact',
    navPlans: 'Plans',
    dropdown01: 'More',
    navAboutUs: 'About us',
    navTerms: 'Term & Conditions',
    navPrivacy: 'Privacy Policy',
    pageTitle1: 'We turn ideas into reality, bringing exceptional creativity to power your business. Be unique, stand out from the competition and reach your target audience in a memorable way. Lets make your brand a successful reference.',
    pageTitleButton: 'Learn More',
    FormTittle: 'Just fill out the form and we\'ll call you',
    FormP1: 'Are you ready to take your business to the next level? Just click the button below to contact us and our team will be in touch shortly. We\'re excited to discuss your unique business needs, develop innovative ideas, and create a customized marketing strategy that drives results.',
    FormTitleP2:'<strong>Innovative solutions: </strong>We pride ourselves on being at the forefront of innovation. When you reach out to us, we\'ll provide you with fresh and creative ideas to make your brand stand out from the competition.',
    FormTitleP3:'<strong>Personalized Attention: </strong> Your success is our priority. When you get in touch with us, we\'ll give you the personalized attention you deserve.',
    FormTitleP4:'<strong>Collaboration:</strong> We believe in the power of collaboration. By reaching out to us, you\'ll have the opportunity to collaborate with our dedicated team. We value your input and insights, and together, we\'ll create a strong partnership to achieve long-term success for your brand.',
    FormName:'Name',
    FormPhone:'Phone',
    FormInterested:'Interested in...',
    PrivacyTerms: 'I agree with the <a href="privacy.html">Privacy Policy</a> and <a href="terms.html">Terms & Conditions',
    FormInquireButton: 'Request a quote',
    SolutionsH1: 'U-Innova Studios: Powering Business Growth with Software, Marketing, Web Design, Graphic Design, and Digital Media Solutions.',
    SoftwareSolution: 'We offer a customized software solution for the efficient management of your business. Our advanced program simplifies and automates key processes, from managing leads, inventory, users to tracking your business growth.',
    MarketingSolution: 'We offer a comprehensive marketing solution to help your business stand out in the marketplace. Our custom solution combines creative strategies, data analytics and technology to boost your online presence, increase brand awareness and attract qualified customers.',
    Details1: 'Driving Your Success with Marketing, Design, and Software Solutions.',
    DetaisP1: 'Increase your online presence, acquire customers and accelerate your business. Discover innovation and creativity at your fingertips with <a href="#your-link">U-Innova Studios',
    Details2: 'Management software with customized solutions',
    DetaisP2: 'With robust applicant tracking, project management and integrated communication features, our <a target="_blank" href="https://u-innova.herokuapp.com/"><b>software</b></ a> allows companies to optimize their operational efficiency, improve service quality.',
    SolutionsH2: 'U-innova Management Software',
    pHeading1: 'U-innova studios has developed innovative software that will drive your company\'s success.',
    pHeading2: 'With the u-innova software you will have:',
    faIcon1: 'Employee and Candidate Management',
    faIcon2: 'Detailed reports and profiles',
    faIcon3: 'Management panel for each user',
    faIcon4: 'Job and workplace management',
    faIcon5: 'Database with daily backup',
    faIcon6: 'Easy viewing of active and/or inactive candidates',
    faIcon7: 'Control of registrations under review',
    faIcon8: 'Performance statistics and error monitoring',
    FutureFeaturesTitle: 'FUTURE FEATURES',
    FutureFeatures1: 'Yuukyu control',
    FutureFeatures2: 'Salary and extra hours control',
    FutureFeatures3: 'Day off request',
    FutureFeatures4: 'Signing of contracts',
    FutureFeatures5: 'Down payment request',
    PlansTitle: 'Plans',
    PlansSubTitle: 'Service Packages',
    BasicPlan: 'BASIC',
    BasicPlanTitle: 'Software Solution for Business Management',
    BasicPlan1: '• Specialized technical support',
    BasicPlan2: '• Social media management',
    BasicPlan3: '• Análise de dados e relatórios de desempenho',
    InquirePlansButton1: 'Inquire',
    AdvancedPlan: 'ADVANCED',
    AdvancedPlanTitle: 'Social Media Management, Digital Marketing and Arts',
    AdvancedPlan1: '• Social media management',
    AdvancedPlan2: '• Design creation for social media posts',
    AdvancedPlan3: '• Boosting posts on social medias',
    AdvancedPlan4: '• Design of digital and printed material (e.g. flyers, business cards, banners)',
    AdvancedPlan5: '• Production and delivery of printed materials',
    InquirePlansButton2: 'Inquire',
    CompletePlan: 'COMPLETE',
    CompletePlanTitle: 'Customized Solution for Software, Digital Marketing and Graphic Design',
    CompletePlan1: '*Everything the BASIC and ADVANCED plan has',
    CompletePlan2: '• Customized marketing campaigns',
    CompletePlan3: '• Website / landing page design',
    CompletePlan4: '• SEO optimization (Search Engine Optimization)',
    CompletePlan5: '• Data analysis and campaign performance monitoring',
    InquirePlansButton3: 'Inquire',
    cassianoAboutIndex: 'Backend software engineer with experience in developing management solutions for real estate in Tokyo. Graduated from Le Wagon as a full stack engineer.',
    narumiAboutIndex: 'Professional passionate about web design, also with experience in the areas of graphic design, digital marketing, digital media and front-end development.',
    aboutUsBtn1: 'About us <span class="material-symbols-outlined"><i class="fa-solid fa-arrow-right"></i>',
    aboutUsBtn2: 'About us <span class="material-symbols-outlined"><i class="fa-solid fa-arrow-right"></i>',
    testimonial1: 'U-Innova\'s software has revolutionized our contractor management. Now we can easily track and manage our employees and candidates in one place, making the whole process more efficient.</p><p class="testimonial-author"> Recruitment company</p>',
    testimonial2: 'The individual management panel for each tantousha in the U-Innova software is amazing. Now we can customize and control the activities of each team member, ensuring an efficient distribution of tasks and optimizing our productivity.</p><p class ="testimonial-author">Recruitment company</p>',
    testimonial3: 'Management of jobs and workplace has never been easier. We can quickly assign jobs to candidates and track the progress of each project, keeping everyone in the loop.</p><p class="testimonial-author"> Hiring Manager </p>',
    testimonial4: 'The database integrated into the U-Innova software is a real lifesaver. We now have all candidate and employee information stored in an organized and accessible way, streamlining our workflow.</p><p class= "testimonial-author">Satisfied customer</p>',
    testimonial5: 'Easy viewing of active and/or inactive candidates is one of the most useful features of the software. We can quickly identify candidates who are available for future assignments, streamlining our selection process.</p><p class="testimonial- author">Recruitment company</p>',
    testimonial6: 'The control of records under review in the U-Innova software is an essential feature. Now we can review, approve and update contractors\' records quickly and efficiently, keeping our database always up to date.</p><p class="testimonial-author">Human Resources Manager</p>',
    Statistics1: 'Satisfied Customers',
    Statistics2: 'Solved Problems',
    Statistics3: 'Positive Reviews',
    Statistics4: 'Case Studies',
    MissionLP: 'Our mission is to provide innovative software and digital marketing solutions that empower our customers to succeed in an ever-evolving digital world.',
    AboutUsBtn3:'About Us',
    SubscribeAndFollowButton: 'Subscribe and Follow',
    SubscribeAndFollowText: 'Stay on top of news from U-Innova Studios! Follow us on <a href="#your-link">instagram</a> and like us on <a href="#your-link">Facebook</a> Join our digital community and make part of our journey of innovation and growth!',
    TalkWithUs: 'Contact Us',
    aboutWebsite: 'About Website',
    aboutWebsiteText: 'Welcome to the U-Innova Studios website! We are a company passionate about innovation, software and digital marketing. Our mission is to drive our clients\' success by providing creative and effective solutions. Explore our site to find out how we can help transform your business in the digital world!',
    ContactUsFooter: 'Contact Us',

    //About Us page

    AboutUsTittle: 'About Us',
    CassianoDescription:'Backend software engineer with experience in developing management solutions for real estate in Tokyo. A graduate of Le Wagon as a full stack engineer, he has comprehensive software development skills. I have significant experience in developing management solutions for people, as well as knowledge in information security and data infrastructure. My passion for technology and my commitment to excellence drive me to create efficient and secure solutions to meet market needs.',
    NarumiDescription:'With experience in the areas of web design, graphic design, digital marketing, digital media and front-end development, I have technical skills to transform concepts into attractive and functional interfaces. My passion for graphic design allows me to create impactful layouts that communicate the essence of the brand. With knowledge in digital marketing and digital media, I am able to develop effective strategies to promote online businesses and reach the target audience efficiently. I am always up to date with the latest industry trends and best practices, constantly looking to improve my skills to deliver high quality projects.',

    //Policy & Privacy page

    PrivacyTitle: 'Privacy Policy',
    PrivacyP1: 'The privacy of our visitors is very important to us. This privacy policy describes how we collect, use, disclose and protect the personal information you provide to us when using the U-Innova Studios website.',
    PrivacyP2: 'We collect information that you voluntarily provide when completing our contact form, including your name, email address and telephone number. This information is collected for the purpose of contacting you and providing you with information about our services.',
    PrivacyP3: 'The information we collect is used solely to contact you and provide you with relevant information about our marketing and advertising services. We do not share your personal information with third parties, except when necessary to comply with legal obligations or with your express consent.',
    PrivacyP4: 'We implement appropriate security measures to protect your information from unauthorized access, misuse or disclosure. We adopt information security practices to guarantee the integrity and confidentiality of the collected data.',
    PrivacyP5: 'Our website may use cookies to improve your user experience. Cookies are small text files stored on your device that allow us to recognize specific information about your visit to the website. You can choose to disable cookies in your browser settings, however this may affect the correct functioning of the website.',
    PrivacyP6: 'The U-Innova Studios website may contain links to third party websites. This privacy policy applies exclusively to our website. We are not responsible for the privacy practices of these sites. We recommend that you read the privacy policies of these sites before providing any personal information.',
    PrivacyP7: 'By using the U-Innova Studios website and providing your personal information, you agree to the collection, use and disclosure of this information in accordance with this privacy policy.',
    PrivacyP8: 'We reserve the right to update or modify this privacy policy at any time. We recommend that you review this policy periodically to stay informed of any changes. Your continued use of the website following the posting of changes constitutes your consent to such changes.',
    PrivacyP9: 'If you have any questions or concerns about our privacy policy or the processing of your personal data, please contact us using the information provided on the website.',
    Privacyh1: '1. Information collection',
    Privacyh2: '2. Use of information',
    Privacyh3: 'Information protection',
    Privacyh4: 'Cookies',
    Privacyh5: 'Links to Third Party Sites',
    Privacyh6: 'Consent',
    Privacyh7: 'Changes to the privacy policy',
    Privacyh8: 'Contact',

    //Terms

    TermsTittle: 'Terms & Condition',
    TermsP1: 'By accessing and using the U-Innova Studios website, you agree to comply with these terms and conditions of use. If you do not agree with any of the terms described below, we recommend that you stop using the site.',
    TermsP2: 'The U-Innova Studios website is intended to provide information about our marketing and advertising services. You agree to use the site only for legitimate purposes and in accordance with all applicable laws and regulations.',
    TermsP3: 'By completing our contact form, you agree to provide accurate and up-to-date information, including your name, email address and telephone number. This information is collected for the purpose of contacting you and providing you with information about our services. We respect your privacy and do not share your personal information with third parties, except when necessary to comply with legal obligations or with your express consent.',
    TermsP4: 'All copyrights, trademarks and other intellectual property rights relating to the content and design of the U-Innova Studios website are the exclusive property of our company or duly authorized third parties. It is forbidden to copy, reproduce, modify, distribute or use any content on the website without our written authorization.',
    TermsP5: 'The U-Innova Studios website may contain links to third party websites. These links are provided for convenience only and do not imply an endorsement or responsibility for the contents of these sites. We recommend that you review the terms and conditions and privacy policies of these sites before using them.',
    TermsP6: 'The U-Innova Studios website is provided "as is" and makes no warranties of any kind, express or implied. We are not responsible for any direct, indirect, incidental, consequential or punitive damages arising from the use or inability to use the website.',
    TermsP7: 'We reserve the right to update or modify these terms and conditions at any time without notice. We recommend that you periodically review this page to stay up to date on any changes. Your continued use of the site following the posting of changes constitutes your acceptance of those changes.',
    TermsP8: 'These terms and conditions are governed by the laws of Brazil. Any dispute relating to the use of the U-Innova Studios website will be subject to the exclusive jurisdiction of the competent courts in Brazil.',
    hTerms1: '1. Use of the website',
    hTerms2: '2. Contact information',
    hTerms3: 'Propriedade intelectual',
    hTerms4: 'Links to Third Party Sites',
    hTerms5: 'Limitation of Liability',
    hTerms6: 'Changes to terms and conditions',
    hTerms7: 'Applicable law and jurisdiction',


    english: 'English',
    portuguese: 'Português',
  }

};

function translatePage(language) {
  const data = languageData[language];

  for (const key in data) {
    if (data.hasOwnProperty(key)) {
      const element = document.getElementById(key);
      if (element) {
        element.innerHTML = data[key];
      }
    }
  }
}

function changeLanguage(lang) {
  translatePage(lang);
}
